### PR TITLE
feat: Adding Docker Support

### PR DESCRIPTION
**Pull request by MarcOrfilaCarreras**
I've been impressed with your work and would like to contribute in order to enhance the project's deployment and development process.

I've made the following changes to your project:

Added Dockerfile: This file includes the necessary instructions to build a Docker image for the application. It specifies the base image, required dependencies, and sets up the environment.

Added docker-compose.yml: This file defines the services, networks, and configurations needed to orchestrate the containers for the application. It simplifies the process of setting up the development environment.

Added entrypoint.py: This script acts as the entry point for the application within the Docker container. It ensures that the required processes are started correctly upon container launch.

These changes allow your project to be run smoothly within a Docker container, making it more portable across different environments and simplifying the setup process.

I've tested these changes on my own system. Please review them and test in your environment to make sure they work well for you too.

### CODE REVIEW

**Comment by leodev12345** [comment]
Hello, thanks for contributing, I will have to test this but I have never used docker before so I will have to learn some basics first, but its a good idea to make this app compatable with docker for easier deployment so thanks

**Comment by MarcOrfilaCarreras** [comment]
I’m glad you found the changes useful! Docker can indeed simplify deployment and development processes. In the self-hosted community, many users rely on Docker for its portability and consistency across different environments. It’s great that you’re open to the idea of using Docker for your project.

You could use GitHub Actions to implement an automated process to push a new Docker image to a repository with every version updadate.

**Comment by MarcOrfilaCarreras** [comment]
@leodev12345  Any news on the PR?

**Comment by leodev12345** [comment]
@MarcOrfilaCarreras I finally added docker support, I know its very late but I finally learned how docker works, I used some of the code you provided but modified a lot, thanks for the idea tho.

**Pull request closed without merging**
